version: git-{branch}-{build}
configuration: Debug-v120


image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x86
  - x64

build:
  project: shell/reicast.sln
  parallel: true
  verbosity: minimal

configuration:
  - Debug-v120
  - Debug-v140
  - Debug-v141
  - Release-v120
  - Release-v140
  - Release-v141

matrix:
  exclude:
    - configuration: Debug-v120
      image: Visual Studio 2015
      image: Visual Studio 2017
    - configuration: Release-v120
      image: Visual Studio 2015
      image: Visual Studio 2017
    - configuration: Debug-v140
      image: Visual Studio 2013
    - configuration: Release-v140
      image: Visual Studio 2013
    - configuration: Debug-v141
      image: Visual Studio 2013
      image: Visual Studio 2015
    - configuration: Release-v141
      image: Visual Studio 2013
      image: Visual Studio 2015


after_build:
  - cmd: mkdir artifacts
  - cmd: set PLATFORM2=%PLATFORM:x86=Win32%
  - cmd: move WorkDir\reicast_%PLATFORM2%_Slow.exe artifacts/reicast-win_%PLATFORM%-slow-%APPVEYOR_REPO_COMMIT%.exe

artifacts:
  - path: artifacts
    name: reicast-win_$(platform)-slow-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: S3
  access_key_id: AKIAJETEBUZSLZF3YNKA
  secret_access_key:
    secure: ZxrysCeqMK99dOOzKyoeN4R5aO8JjA4RTrwVAQPQHz8sjyyKuVDZT2fC+9m6lUIi
  region: eu-west-1
  bucket: reicast-builds-windows
  folder: 'builds/heads/$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT)'
  artifact: reicast-win_$(platform)-slow-$(APPVEYOR_REPO_COMMIT)
  set_public: true
